-- ============================================================================
-- IE-Eff — Khởi tạo toàn bộ bảng dữ liệu (PostgreSQL 15+)
-- ----------------------------------------------------------------------------
-- Tạo đủ 14 bảng của ứng dụng: khóa chính, ràng buộc UNIQUE, khóa ngoại, index.
--
-- Cách dùng:
--   * install.bat tự động chạy file này sau khi tạo database — không cần làm tay.
--   * Chạy thủ công (nếu cần):
--       psql -U ie_app -h localhost -d shoe_eff_db -f init_db.sql
--
-- Ghi chú:
--   * Schema này khớp CHÍNH XÁC với các JPA entity (đã đối chiếu trực tiếp với
--     database đang chạy). Profile "prod" dùng hibernate ddl-auto=validate sẽ
--     kiểm tra schema này và khởi động bình thường.
--   * KHÔNG dùng các file Flyway trong src/main/resources/db/migration/ để tạo
--     database từ đầu — chúng thiếu 3 bảng (new_style_entry, eff_incentive_rate,
--     eff_multiplier) nên không đầy đủ.
--   * Các bảng của Quartz scheduler (qrtz_*) KHÔNG nằm ở đây — ứng dụng tự tạo
--     khi khởi động lần đầu.
--   * Dùng CREATE TABLE IF NOT EXISTS nên chạy lại nhiều lần vẫn an toàn.
--   * Nếu sau này sửa JPA entity, tạo lại file này bằng:
--       pg_dump -U postgres -h localhost -d shoe_eff_db --schema-only \
--               --no-owner --no-privileges -T 'qrtz*'
-- ============================================================================

SET client_encoding = 'UTF8';

-- ─── users ──────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
    id       bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username varchar(50)  NOT NULL,
    password varchar(255) NOT NULL,
    role     varchar(255) NOT NULL,
    CONSTRAINT uq_users_username UNIQUE (username)
);

-- ─── daily_production ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS daily_production (
    id              bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_date date             NOT NULL,
    section         varchar(255)     NOT NULL,
    line            varchar(255)     NOT NULL,
    mp              double precision NOT NULL,
    dli             double precision,
    idl             double precision,
    wt              double precision NOT NULL,
    rft             double precision,
    allowance       double precision NOT NULL,
    total_output    integer          NOT NULL,
    version         bigint,
    user_id         bigint           NOT NULL,
    created_at      timestamp(6)     NOT NULL,
    updated_at      timestamp(6),
    CONSTRAINT fk_dp_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_dp_production_date   ON daily_production (production_date);
CREATE INDEX IF NOT EXISTS idx_dp_user_id           ON daily_production (user_id);
CREATE INDEX IF NOT EXISTS idx_dp_section_line      ON daily_production (section, line);
CREATE INDEX IF NOT EXISTS idx_dp_date_section_line ON daily_production (production_date, section, line);

-- ─── daily_production_details ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS daily_production_details (
    id                  bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    daily_production_id bigint       NOT NULL,
    time_slot           varchar(255) NOT NULL,
    article_no          varchar(255) NOT NULL,
    output              integer      NOT NULL,
    CONSTRAINT uq_dpd_prod_slot UNIQUE (daily_production_id, time_slot),
    CONSTRAINT fk_dpd_production FOREIGN KEY (daily_production_id) REFERENCES daily_production (id)
);

-- ─── split_entry ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS split_entry (
    id                         bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    production_date            date             NOT NULL,
    section                    varchar(255)     NOT NULL,
    line                       varchar(255)     NOT NULL,
    mp                         double precision,
    dli                        double precision,
    idl                        double precision,
    wt                         double precision,
    rft                        double precision,
    allowance                  double precision,
    total_output               integer,
    status                     varchar(10)      NOT NULL,
    version                    bigint,
    manpower_filled_by         bigint,
    output_filled_by           bigint,
    article_filled_by          bigint,
    linked_daily_production_id bigint,
    created_at                 timestamp(6)     NOT NULL,
    updated_at                 timestamp(6),
    CONSTRAINT uq_split_entry_date_section_line UNIQUE (production_date, section, line),
    CONSTRAINT fk_se_manpower_user FOREIGN KEY (manpower_filled_by) REFERENCES users (id),
    CONSTRAINT fk_se_output_user   FOREIGN KEY (output_filled_by)   REFERENCES users (id),
    CONSTRAINT fk_se_article_user  FOREIGN KEY (article_filled_by)  REFERENCES users (id)
);

CREATE INDEX IF NOT EXISTS idx_se_production_date ON split_entry (production_date);
CREATE INDEX IF NOT EXISTS idx_se_status          ON split_entry (status);
CREATE INDEX IF NOT EXISTS idx_se_section_line    ON split_entry (section, line);

-- ─── split_entry_details ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS split_entry_details (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    split_entry_id bigint       NOT NULL,
    time_slot      varchar(255) NOT NULL,
    article_no     varchar(255) NOT NULL,
    output         integer      NOT NULL,
    CONSTRAINT uq_sed_entry_slot UNIQUE (split_entry_id, time_slot),
    CONSTRAINT fk_sed_split_entry FOREIGN KEY (split_entry_id) REFERENCES split_entry (id)
);

-- ─── master_db ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS master_db (
    id                   bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref                  varchar(255)     NOT NULL,
    data_month           varchar(7),
    article_no           varchar(255)     NOT NULL,
    pattern_no           varchar(255),
    shoe_name            varchar(255),
    os_code              varchar(255),
    tct                  double precision,
    sew_ct               double precision,
    sew_mp               double precision,
    sew_quota_db         double precision,
    sew_pph              double precision,
    buff1st_ct           double precision,
    buff1st_mp           double precision,
    buff1st_quota_db     double precision,
    buff1st_pph          double precision,
    buff2nd_ct           double precision,
    buff2nd_mp           double precision,
    buff2nd_quota_db     double precision,
    buff2nd_pph          double precision,
    stockfit_uv_ct       double precision,
    stockfit_uv_mp       double precision,
    stockfit_uv_quota_db double precision,
    stockfit_uv_pph      double precision,
    stockfit1st_ct       double precision,
    stockfit1st_mp       double precision,
    stockfit1st_quota_db double precision,
    stockfit1st_pph      double precision,
    stockfit2nd_ct       double precision,
    stockfit2nd_mp       double precision,
    stockfit2nd_quota_db double precision,
    stockfit2nd_pph      double precision,
    assem_big_ct         double precision,
    assem_big_mp         double precision,
    assem_big_quota_db   double precision,
    assem_big_pph        double precision,
    assem_small_ct       double precision,
    assem_small_mp       double precision,
    assem_small_quota_db double precision,
    assem_small_pph      double precision,
    CONSTRAINT uq_master_db_ref_month UNIQUE (ref, data_month)
);

CREATE INDEX IF NOT EXISTS idx_mdb_article_no ON master_db (article_no);
CREATE INDEX IF NOT EXISTS idx_mdb_data_month ON master_db (data_month);

-- ─── new_style_entry ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS new_style_entry (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section    varchar(20) NOT NULL,
    line       varchar(10) NOT NULL,
    style      varchar(50) NOT NULL,
    quantity   integer     NOT NULL,
    data_month varchar(7)
);

-- ─── notifications ──────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
    id             bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_role varchar(255) NOT NULL,
    title          varchar(255) NOT NULL,
    message        text,
    type           varchar(255) NOT NULL,
    is_read        boolean,
    created_at     timestamp(6)
);

CREATE INDEX IF NOT EXISTS idx_notif_role_read  ON notifications (recipient_role, is_read);
CREATE INDEX IF NOT EXISTS idx_notif_created_at ON notifications (created_at);

-- ─── system_logs ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS system_logs (
    id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username    varchar(255) NOT NULL,
    action      varchar(255) NOT NULL,
    details     text,
    ip_address  varchar(45),
    "timestamp" timestamp(6) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_syslog_timestamp ON system_logs ("timestamp");

-- ─── sixs_record ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sixs_record (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_month varchar(7)  NOT NULL,
    section    varchar(20) NOT NULL,
    line       varchar(10) NOT NULL,
    week1      integer,
    week2      integer,
    week3      integer,
    week4      integer,
    week5      integer,
    CONSTRAINT uq_sixs_month_sec_line UNIQUE (data_month, section, line)
);

-- ─── reprocess_record ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reprocess_record (
    id         bigint      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_month varchar(7)  NOT NULL,
    section    varchar(20) NOT NULL,
    line       varchar(10) NOT NULL,
    week1      integer,
    week2      integer,
    week3      integer,
    week4      integer,
    week5      integer,
    output     integer,
    CONSTRAINT uq_reprocess_month_sec_line UNIQUE (data_month, section, line)
);

-- ─── eff_incentive_rate ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS eff_incentive_rate (
    id          bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section     varchar(10)      NOT NULL,
    sec         varchar(10)      NOT NULL,
    wt          integer          NOT NULL,
    eff_percent double precision NOT NULL,
    rate        double precision NOT NULL,
    CONSTRAINT uq_eff_incentive_sec_pct UNIQUE (sec, eff_percent)
);

-- ─── eff_multiplier ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS eff_multiplier (
    id         bigint           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section    varchar(10)      NOT NULL,
    sec        varchar(10)      NOT NULL,
    wt         integer          NOT NULL,
    rate_alias varchar(10),
    grade1     double precision,
    grade2     double precision,
    grade3     double precision,
    grade4     double precision,
    grade5     double precision,
    grade6     double precision,
    grade7     double precision,
    grade8     double precision,
    grade9     double precision,
    CONSTRAINT uq_eff_multiplier_sec UNIQUE (sec)
);

-- ─── import_jobs ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS import_jobs (
    id            bigint                      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type      varchar(50)                 NOT NULL,
    status        varchar(20)                 NOT NULL,
    progress      integer                     NOT NULL,
    total_rows    integer                     NOT NULL,
    error_message text,
    created_by    varchar(100),
    created_at    timestamp(6) with time zone NOT NULL,
    updated_at    timestamp(6) with time zone NOT NULL
);
