-- ============================================================
-- V10__add_user_line_assignments.sql
-- Data-level (row) authorization: restrict which production
-- (section, line) a user may enter data for.
--   line = ''  -> whole section (every line in it)
-- A user with zero rows is unrestricted; the restriction only
-- activates once at least one assignment exists. ADMIN/MANAGER
-- are always exempt (enforced in the service layer).
-- ============================================================

CREATE TABLE user_line_assignments (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT       NOT NULL,
    section VARCHAR(50)  NOT NULL,
    line    VARCHAR(50)  NOT NULL DEFAULT '',
    CONSTRAINT pk_user_line_assignments PRIMARY KEY (id),
    CONSTRAINT uk_ula_user_section_line UNIQUE (user_id, section, line),
    CONSTRAINT fk_ula_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_ula_user ON user_line_assignments (user_id);
