-- ============================================================
-- V17__idempotent_catchup_v10_v16.sql
-- Flyway chỉ mới được kích hoạt thật sự từ bây giờ (Spring Boot 4 cần module
-- spring-boot-flyway; trước đó migrations không hề chạy lúc boot — schema được
-- ddl-auto=update (dev) hoặc chạy SQL tay (prod) tạo). DB hiện có được baseline
-- ở V16, nên V17 này vá idempotent mọi object của V10..V16: cái gì có rồi thì
-- bỏ qua, cái gì thiếu thì tạo. DB rỗng chạy đủ V1..V16 nên V17 chỉ no-op.
-- ============================================================

-- ─── Bảng Hibernate-era chưa từng có CREATE migration ────────
-- (new_style_entry / eff_incentive_rate / eff_multiplier được ddl-auto=update tạo
--  trước khi Flyway hoạt động; V3/V4 chỉ ALTER có điều kiện. Tạo ở đây theo shape
--  cuối của entity để DB rỗng chạy đủ chuỗi + prod validate khớp.)
CREATE TABLE IF NOT EXISTS new_style_entry (
    id         BIGSERIAL    NOT NULL,
    data_month VARCHAR(7)   NOT NULL,
    section    VARCHAR(20)  NOT NULL,
    line       VARCHAR(10)  NOT NULL,
    style      VARCHAR(50)  NOT NULL,
    quantity   INTEGER      NOT NULL,
    CONSTRAINT pk_new_style_entry PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS eff_incentive_rate (
    id          BIGSERIAL        NOT NULL,
    sec         VARCHAR(10)      NOT NULL,
    section     VARCHAR(10)      NOT NULL,
    wt          INTEGER          NOT NULL,
    eff_percent DOUBLE PRECISION NOT NULL,
    rate        DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_eff_incentive_rate PRIMARY KEY (id),
    CONSTRAINT uq_eff_incentive_rate UNIQUE (sec, eff_percent)
);

CREATE TABLE IF NOT EXISTS eff_multiplier (
    id         BIGSERIAL        NOT NULL,
    sec        VARCHAR(10)      NOT NULL,
    section    VARCHAR(10)      NOT NULL,
    wt         INTEGER          NOT NULL,
    rate_alias VARCHAR(10),
    grade1     DOUBLE PRECISION,
    grade2     DOUBLE PRECISION,
    grade3     DOUBLE PRECISION,
    grade4     DOUBLE PRECISION,
    grade5     DOUBLE PRECISION,
    grade6     DOUBLE PRECISION,
    grade7     DOUBLE PRECISION,
    grade8     DOUBLE PRECISION,
    grade9     DOUBLE PRECISION,
    CONSTRAINT pk_eff_multiplier PRIMARY KEY (id),
    CONSTRAINT uq_eff_multiplier_sec UNIQUE (sec)
);

-- ─── V10: user_line_assignments ─────────────────────────────
CREATE TABLE IF NOT EXISTS user_line_assignments (
    id      BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT       NOT NULL,
    section VARCHAR(50)  NOT NULL,
    line    VARCHAR(50)  NOT NULL DEFAULT '',
    CONSTRAINT pk_user_line_assignments PRIMARY KEY (id),
    CONSTRAINT uk_ula_user_section_line UNIQUE (user_id, section, line),
    CONSTRAINT fk_ula_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_ula_user ON user_line_assignments (user_id);

-- ─── V11: salary → incentive routes (UPDATE, chạy lại vô hại) ─
UPDATE features
SET url_patterns = '/incentive/**,/api/v1/incentive/**',
    display_name = 'Incentive'
WHERE feature_key = 'SALARY';

-- ─── V12: voc_chemical + voc_consumption + feature VOC ───────
CREATE TABLE IF NOT EXISTS voc_chemical (
    id             BIGSERIAL        NOT NULL,
    code           VARCHAR(40)      NOT NULL,
    material_type  VARCHAR(20)      NOT NULL DEFAULT 'SOLVENT',
    classification VARCHAR(40),
    manufacturer   VARCHAR(60),
    voc_factor     DOUBLE PRECISION NOT NULL DEFAULT 0,
    price_per_kg   DOUBLE PRECISION,
    active         BOOLEAN          NOT NULL DEFAULT TRUE,
    created_at     TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP(6),
    CONSTRAINT pk_voc_chemical PRIMARY KEY (id),
    CONSTRAINT uq_voc_chemical_code UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS voc_consumption (
    id              BIGSERIAL        NOT NULL,
    version         BIGINT,
    production_date DATE             NOT NULL,
    section         VARCHAR(20)      NOT NULL DEFAULT 'SEW',
    line            VARCHAR(10)      NOT NULL,
    chemical_code   VARCHAR(40)      NOT NULL,
    quantity_kg     DOUBLE PRECISION NOT NULL DEFAULT 0,
    reuse_kg        DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6),
    CONSTRAINT pk_voc_consumption PRIMARY KEY (id),
    CONSTRAINT uq_voc_consumption UNIQUE (production_date, section, line, chemical_code)
);
CREATE INDEX IF NOT EXISTS idx_voc_cons_date          ON voc_consumption (production_date);
CREATE INDEX IF NOT EXISTS idx_voc_cons_date_sec_line ON voc_consumption (production_date, section, line);

INSERT INTO features (feature_key, display_name, url_patterns, http_methods, category, priority)
SELECT 'VOC', 'VOC', '/voc/**,/api/v1/voc/**', NULL, 'Analytics', 500
WHERE NOT EXISTS (SELECT 1 FROM features WHERE feature_key = 'VOC');

INSERT INTO role_features (role_id, feature_id)
SELECT r.id, f.id
FROM roles r
CROSS JOIN features f
WHERE r.name IN ('ROLE_ADMIN', 'ROLE_MANAGER')
  AND f.feature_key = 'VOC'
  AND NOT EXISTS (SELECT 1 FROM role_features rf WHERE rf.role_id = r.id AND rf.feature_id = f.id);

-- ─── V13: voc_standard_rate ──────────────────────────────────
CREATE TABLE IF NOT EXISTS voc_standard_rate (
    id            BIGSERIAL        NOT NULL,
    article_no    VARCHAR(40)      NOT NULL,
    chemical_code VARCHAR(40)      NOT NULL,
    kg_per_pair   DOUBLE PRECISION NOT NULL DEFAULT 0,
    created_at    TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(6),
    CONSTRAINT pk_voc_standard_rate PRIMARY KEY (id),
    CONSTRAINT uq_voc_std_rate UNIQUE (article_no, chemical_code)
);
CREATE INDEX IF NOT EXISTS idx_voc_std_rate_article ON voc_standard_rate (article_no);

-- ─── V14: formula + voc_recipe_article ───────────────────────
ALTER TABLE voc_standard_rate ADD COLUMN IF NOT EXISTS formula VARCHAR(255);

CREATE TABLE IF NOT EXISTS voc_recipe_article (
    article_no  VARCHAR(40)      NOT NULL,
    model_code  VARCHAR(60),
    model_name  VARCHAR(160),
    base_e      DOUBLE PRECISION,
    base_f      DOUBLE PRECISION,
    created_at  TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(6),
    CONSTRAINT pk_voc_recipe_article PRIMARY KEY (article_no)
);

-- created_at tường minh: bảng do Hibernate tạo (dev) không có DB DEFAULT cho cột này
INSERT INTO voc_recipe_article (article_no, created_at)
SELECT DISTINCT article_no, CURRENT_TIMESTAMP FROM voc_standard_rate
ON CONFLICT (article_no) DO NOTHING;

-- ─── V15: cột tham chiếu sheet R trên voc_chemical ───────────
ALTER TABLE voc_chemical ADD COLUMN IF NOT EXISTS unit              VARCHAR(20);
ALTER TABLE voc_chemical ADD COLUMN IF NOT EXISTS container_size_kg DOUBLE PRECISION;
ALTER TABLE voc_chemical ADD COLUMN IF NOT EXISTS container_price   DOUBLE PRECISION;
ALTER TABLE voc_chemical ADD COLUMN IF NOT EXISTS price_ref_note    VARCHAR(60);

-- ─── V16: SUBCON (CEMENT) ────────────────────────────────────
CREATE TABLE IF NOT EXISTS voc_subcon_entry (
    id              BIGSERIAL        NOT NULL,
    version         BIGINT,
    production_date DATE             NOT NULL,
    subcontractor   VARCHAR(40)      NOT NULL,
    article_no      VARCHAR(40)      NOT NULL,
    output          INTEGER          NOT NULL DEFAULT 0,
    created_at      TIMESTAMP(6)     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP(6),
    CONSTRAINT pk_voc_subcon_entry PRIMARY KEY (id),
    CONSTRAINT uq_voc_subcon_entry UNIQUE (production_date, subcontractor, article_no)
);
CREATE INDEX IF NOT EXISTS idx_voc_subcon_entry_date ON voc_subcon_entry (production_date);

CREATE TABLE IF NOT EXISTS voc_subcon_detail (
    id            BIGSERIAL        NOT NULL,
    entry_id      BIGINT           NOT NULL,
    chemical_code VARCHAR(40)      NOT NULL,
    actual_kg     DOUBLE PRECISION NOT NULL DEFAULT 0,
    reuse_kg      DOUBLE PRECISION NOT NULL DEFAULT 0,
    CONSTRAINT pk_voc_subcon_detail PRIMARY KEY (id),
    CONSTRAINT uq_voc_subcon_detail UNIQUE (entry_id, chemical_code),
    CONSTRAINT fk_voc_subcon_detail_entry FOREIGN KEY (entry_id)
        REFERENCES voc_subcon_entry (id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_voc_subcon_detail_entry ON voc_subcon_detail (entry_id);
